/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.*;
import org.junit.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class TodoTest {
    private static ChromeDriver driver;


    @BeforeAll
    static void launchBrowser() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
    }

    // Your tests will go here!
    @Test
    void getTitleFromPage() {
        driver.get("https://todomvc.com/");
        Assert.assertEquals("TodoMVC", driver.getTitle());
        System.out.println(driver.getTitle());
    }

    @AfterAll
    static void closeBrowser() {
        driver.quit();
    }
}